### ISSUE TITLE
Bower registration

### ISSUE THREAD

**Issue by F2X** [greenplumm/handjs#1]
Hi,
I would like to know if it's possible to register on bower the "official" handjs repository (https://github.com/deltakosh/handjs) instead this one, by asking the author.
In fact I'm trying to get the last version, 1.3.11, but your registered version is in 1.3.8, and bower does'nt allow two packages with the same name, so it's not possible to register the original.
Thanks

**Comment by waffledonkey** [comment]
I agree, it's annoying.  You can just tweak your bower.json to point to the one you want:

```
"dependencies": {
    ...
    "handjs": "https://github.com/deltakosh/handjs.git"
    ...
}
```

**Comment by redoPop** [comment]
Please do this, @greenplumm! This repo was a convenient way to register handjs as a dependency while [the project was housed on CodePlex](https://handjs.codeplex.com/), but it officially moved [to GitHub](https://github.com/deltakosh/handjs/) in May and subsequent updates have been [semver tagged releases](https://github.com/deltakosh/handjs/tree/1.3.9).

Consequently, this clone has become obsolete and out of date, and the registration naming conflict is preventing us from taking advantage of semver range support.

Instructions for unregistering Bower packages [can be found here](http://bower.io/docs/creating-packages/#unregister), but it's a step only you (as the owner of the currently registered repo) can take.
